version: '3.1'

services:

  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - "/var/lib/docker/volumes/postgres-db/_data:/var/lib/postgresql/data"

volumes:
  postgres-db:
