version: '3.9'

services:

  postgres:
    image: postgres:alpine
    container_name: ws_rasmoo_plus_postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    external: true


